version: "3.8"
services:
  frontend:
    image: boilerplate-dockerizing/frontend:${TAG:-latest}
    build:
      context: frontend
    restart: always
    environment:
      PGHOST: rdb
      PGUSER: postgres
      PGDATABASE: example
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
    links:
      - rdb:rdb

  rdb:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: example
    volumes:
      - ./.volatile/pgdata:/var/lib/postgresql/data
      - ./db/rdb/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432
